### ISSUE TITLE
Именования переменных не должно быть с большой буквы

### ISSUE THREAD

**Issue by alexeychernykh** [Swizi/travelline-practice#1]
https://github.com/Swizi/travelline-practice/blob/82fd07e75a30af564a02f22334e2692ee9b16cd1/task_4/ItCompanySimulator/ItCompanySimulator/Program.cs#L24

https://docs.microsoft.com/ru-ru/dotnet/standard/design-guidelines/capitalization-conventions

**Comment by denis-bosiy** [comment]
Исправлено https://github.com/Swizi/travelline-practice/blob/master/task_4/ItCompanySimulator/ItCompanySimulator/Program.cs
