### ISSUE TITLE
Изучить стили именования полей в классе

### ISSUE THREAD

**Issue by alexeychernykh** [Swizi/travelline-practice#2]
https://github.com/Swizi/travelline-practice/blob/82fd07e75a30af564a02f22334e2692ee9b16cd1/task_4/ItCompanySimulator/CompanyLib/Company.cs#L15

Где то с подчёркивание, где то без

**Comment by denis-bosiy** [comment]
Исправлено https://github.com/Swizi/travelline-practice/blob/master/task_4/ItCompanySimulator/CompanyLib/Employee.cs https://github.com/Swizi/travelline-practice/blob/master/task_4/ItCompanySimulator/CompanyLib/Company.cs
