### ISSUE TITLE
Добавить в поведение клиентов больше логики

### ISSUE THREAD

**Issue by alexeychernykh** [Swizi/travelline-practice#3]
https://github.com/Swizi/travelline-practice/blob/82fd07e75a30af564a02f22334e2692ee9b16cd1/task_4/ItCompanySimulator/CompanyLib/GoodClient.cs#L9

Функционально BadClient и GoodClient не отличаются, на выходе только разные строки.
Нужно наполнить их некоторым поведением, чтобы была видна необходимость в разных реализациях.

**Comment by denis-bosiy** [comment]
Исправлено https://github.com/Swizi/travelline-practice/blob/master/task_4/ItCompanySimulator/CompanyLib/Client.cs
