### ISSUE TITLE
Публичные поля, методы и тд. с большой буквы

### ISSUE THREAD

**Issue by alexeychernykh** [Swizi/travelline-practice#6]
https://github.com/Swizi/travelline-practice/blob/cd9bbc5b79e9eb43d47659f44fced0ef9fbc568f/task_4/ItCompanySimulator/CompanyLib/Company.cs#L17

**Comment by denis-bosiy** [comment]
Готово https://github.com/Swizi/travelline-practice/commit/9291c2b6fe969e7fe6c92394fcd01e4bd4841b4d
