### ISSUE TITLE
Не указывать название базы данных в запросе

### ISSUE THREAD

**Issue by alexeychernykh** [Swizi/travelline-practice#7]
https://github.com/Swizi/travelline-practice/blob/6f27b041595ac7fe478bf5f4ee9ef4d73e6ffcb7/task_5/ShopTask/Program.cs#L38

База может называться по разному на разных средах. Название БД указывается только в connectionString

**Comment by denis-bosiy** [comment]
Готово https://github.com/Swizi/travelline-practice/commit/1642ebca7c8297a8160e5b9b5f4c0894425c9740
